import type { Chapter } from '../types';

const translation = 'English translation prepared for this project from the French original.';

/** Sources, edition details, and editorial decisions are recorded in docs/SOURCES.md. */
export const chapters: Chapter[] = [
  {
    id: 1,
    slug: 'a-restless-curiosity',
    title: 'A restless curiosity',
    period: '1909–1925',
    place: 'Paris',
    idea: 'Truth',
    paragraph: 'In a comfortable Paris home, Simone and her brother André grow up among books and difficult questions. Born in 1909 into a secular Jewish family, she measures herself painfully against his mathematical gifts. Yet she comes to believe that truth is open to anyone willing to attend to it. Curiosity becomes a demanding way of life.',
    quote: {
      text: 'By truth I also meant beauty, virtue, and every good.',
      work: 'Spiritual Autobiography',
      locator: 'Letter IV, paragraph on the meaning of truth; Attente de Dieu, La Colombe, 1950, pp. 69–89.',
      translation,
      url: 'https://fr.wikisource.org/wiki/Attente_de_Dieu/Autobiographie_spirituelle',
      note: 'Written to Joseph-Marie Perrin around 15 May 1942, looking back on adolescence; published posthumously.',
    },
    scene: 'models/chapter-01.glb',
    poster: 'posters/chapter-01.webp',
  },
  {
    id: 2,
    slug: 'learning-to-see',
    title: 'Learning to see',
    period: '1925–1931',
    place: 'Paris',
    idea: 'Learning',
    paragraph: 'At school, philosophy offers Simone a discipline for looking closely. She studies with Alain, enters the École normale supérieure, and writes about Descartes. Achievement matters less to her than learning to question her own judgments. Years later, she will describe study as practice in attention: making room for something beyond the answers we already possess.',
    quote: {
      text: 'The intelligence can only be led by desire.',
      work: 'On the Right Use of School Studies',
      locator: 'Paragraph contrasting will and desire; Attente de Dieu, La Colombe, 1950, pp. 113–123.',
      translation,
      url: 'https://fr.wikisource.org/wiki/Attente_de_Dieu/Réflexions_sur_le_bon_usage_des_études_scolaires_en_vue_de_l’Amour_de_Dieu',
      note: 'A later religious reflection, written in 1941–1942; not a quotation from her student years. Published posthumously.',
    },
    scene: 'models/chapter-02.glb',
    poster: 'posters/chapter-02.webp',
  },
  {
    id: 3,
    slug: 'beyond-the-classroom',
    title: 'Beyond the classroom',
    period: '1931–1934',
    place: 'Le Puy · Auxerre · Roanne',
    idea: 'Solidarity',
    paragraph: 'Teaching brings Simone into provincial classrooms, but her questions travel into the streets. She supports workers, joins meetings, and teaches beyond her official lessons. What can philosophy mean to someone without enough money or power? Her commitment is intense, sometimes abrasive. She wants thought to answer to ordinary lives, including lives very different from her own.',
    quote: {
      text: 'The reality of life is not sensation, but activity.',
      work: 'Letter to a Student',
      locator: 'Paragraph on sensation and activity; La Condition ouvrière, Gallimard, 1951, pp. 23–28.',
      translation,
      url: 'https://fr.wikisource.org/wiki/La_Condition_ouvrière/03',
      note: 'Letter dated 1934 in this edition, written after she entered factory work; collected posthumously.',
    },
    scene: 'models/chapter-03.glb',
    poster: 'posters/chapter-03.webp',
  },
  {
    id: 4,
    slug: 'who-holds-the-power',
    title: 'Who holds the power?',
    period: '1932–1934',
    place: 'Germany · France',
    idea: 'Freedom',
    paragraph: 'A journey to Germany sharpens her alarm at the rise of Nazism. She also questions the promises of revolution. Changing rulers, she argues, cannot free people if the machinery of obedience survives. In her study of oppression, power becomes a restless competition that traps those who command as well as those who must obey.',
    quote: {
      text: 'Thus all power is unstable.',
      work: 'Reflections on Liberty and Social Oppression',
      locator: 'Analysis of Oppression, paragraph on the instruments of power; Oppression et Liberté, Gallimard, 1955, pp. 80–112.',
      translation,
      url: 'https://fr.wikisource.org/wiki/Oppression_et_Liberté/05/03',
      note: 'Written in 1934; published in this posthumous collection in 1955.',
    },
    scene: 'models/chapter-04.glb',
    poster: 'posters/chapter-04.webp',
  },
  {
    id: 5,
    slug: 'inside-the-factory',
    title: 'Inside the factory',
    period: '1934–1935',
    place: 'Paris',
    idea: 'Labor',
    paragraph: 'Simone takes leave from teaching and works in factories. Orders, speed, and exhaustion narrow her world to the next task. The experience unsettles her confidence in resistance: humiliation can produce submission instead. She records what the machinery asks of a body and a mind, while recognizing a freedom many colleagues lack—the possibility of leaving.',
    quote: {
      text: 'To think is to go more slowly.',
      work: 'Letter to a Student',
      locator: 'Paragraph describing mechanical work and speed; La Condition ouvrière, Gallimard, 1951, pp. 23–28.',
      translation,
      url: 'https://fr.wikisource.org/wiki/La_Condition_ouvrière/03',
      note: 'Letter dated 1934 in this edition, written from her factory experience; collected posthumously.',
    },
    scene: 'models/chapter-05.glb',
    poster: 'posters/chapter-05.webp',
  },
  {
    id: 6,
    slug: 'a-cause-and-its-cruelty',
    title: 'A cause and its cruelty',
    period: '1936',
    place: 'Barcelona · Aragon',
    idea: 'Conscience',
    paragraph: 'Despite her pacifism, Simone joins an anarchist unit in the Spanish Civil War. A severe accidental burn ends her brief service. What remains is a troubling memory of comrades who could treat killing lightly. Writing later to Georges Bernanos, she refuses the comfort of imagining that a just cause makes everyone who serves it just.',
    quote: {
      text: 'One leaves as a volunteer, with ideas of sacrifice…',
      work: 'Letter to Georges Bernanos',
      locator: 'Paragraph on volunteering; L’Espagnole, Abrüpt, 2018, pp. 31–40.',
      translation,
      url: 'https://fr.wikisource.org/wiki/L’Espagnole/03',
      note: 'Usually dated 1938; a retrospective letter about 1936. The ellipsis marks the continuation into her criticism of the war.',
    },
    scene: 'models/chapter-06.glb',
    poster: 'posters/chapter-06.webp',
  },
  {
    id: 7,
    slug: 'at-the-threshold',
    title: 'At the threshold',
    period: '1935–1938',
    place: 'Portugal · Assisi · Solesmes',
    idea: 'Grace',
    paragraph: 'A procession in Portugal, a chapel in Assisi, and the chanting at Solesmes open unexpected doors. Simone later describes encounters with Christ, including one while reciting a poem by George Herbert. Her spiritual life deepens without resolving every doubt. Drawn toward Christianity, she keeps questioning the Church and the boundaries it places around truth.',
    quote: {
      text: 'Christ himself descended and seized me.',
      work: 'Spiritual Autobiography',
      locator: 'Letter IV, paragraph following the account of Herbert’s poem; Attente de Dieu, La Colombe, 1950, pp. 69–89.',
      translation,
      url: 'https://fr.wikisource.org/wiki/Attente_de_Dieu/Autobiographie_spirituelle',
      note: 'Written around 15 May 1942, recounting her own understanding of the earlier experience; published posthumously.',
    },
    scene: 'models/chapter-07.glb',
    poster: 'posters/chapter-07.webp',
  },
  {
    id: 8,
    slug: 'what-force-makes-of-us',
    title: 'What force makes of us',
    period: '1939–1940',
    place: 'Paris · Marseille',
    idea: 'Force',
    paragraph: 'War returns to Europe. Simone abandons her earlier pacifism and, as German forces advance, leaves Paris with her family. Reading Homer, she finds a language for what violence does to people. The Iliad becomes a mirror: force can turn a living person into an object, while its apparent masters never fully escape its reach.',
    quote: {
      text: 'Force turns anyone subjected to it into a thing.',
      work: 'The Iliad, or the Poem of Force',
      locator: 'Opening definition of force; La Source grecque, Gallimard, 1953, pp. 11–42.',
      translation,
      url: 'https://fr.wikisource.org/wiki/La_Source_grecque/01/L’Iliade,_ou_le_poème_de_la_force',
      note: 'Written in 1939–1940 and published in Cahiers du Sud in 1940–1941, under the name Émile Novis. This French edition is posthumous.',
    },
    scene: 'models/chapter-08.glb',
    poster: 'posters/chapter-08.webp',
  },
  {
    id: 9,
    slug: 'the-work-of-attention',
    title: 'The work of attention',
    period: '1940–1942',
    place: 'Marseille · Ardèche',
    idea: 'Attention',
    paragraph: 'In Marseille, conversations, letters, and notebooks gather around an exacting idea: attention. Simone works in the grape harvest and exchanges thoughts with the priest Joseph-Marie Perrin and the writer Gustave Thibon. To attend to another person is to loosen the grip of one’s own concerns. In her religious thinking, that difficult openness becomes a form of prayer.',
    quote: {
      text: 'Absolutely unmixed attention is prayer.',
      work: 'Gravity and Grace',
      locator: 'Attention and Will, short fragment; La Pesanteur et la Grâce, Plon, 1948, pp. 134–142.',
      translation,
      url: 'https://fr.wikisource.org/wiki/La_Pesanteur_et_la_Grâce/26',
      note: 'From notebooks written in 1940–1942; selected and arranged after her death by Gustave Thibon. The collection first appeared in 1947.',
    },
    scene: 'models/chapter-09.glb',
    poster: 'posters/chapter-09.webp',
  },
  {
    id: 10,
    slug: 'what-gives-us-roots',
    title: 'What gives us roots',
    period: '1942–1943',
    place: 'New York · London',
    idea: 'Belonging',
    paragraph: 'Leaving France takes her through New York to London, where she works for the Free French. She imagines how a damaged society might be rebuilt. People need food and shelter, but also responsibility, truth, and ties to a shared past. The Need for Roots asks what we owe one another before asking what we can claim.',
    quote: {
      text: 'Every human being needs multiple roots.',
      work: 'The Need for Roots',
      locator: 'Part II, Uprootedness, opening paragraph; L’Enracinement, Gallimard, 1949, pp. 43–46.',
      translation,
      url: 'https://fr.wikisource.org/wiki/L’Enracinement/Partie_2',
      note: 'Written in London in 1943; published posthumously in 1949.',
    },
    scene: 'models/chapter-10.glb',
    poster: 'posters/chapter-10.webp',
  },
  {
    id: 11,
    slug: 'the-unfinished-task',
    title: 'The unfinished task',
    period: '1943',
    place: 'London · Ashford',
    idea: 'Obligation',
    paragraph: 'The pages keep accumulating, but her health fails. Tuberculosis and severe undernourishment bring her life to an end in Ashford on 24 August 1943, aged thirty-four. The reasons she ate so little remain debated. Her final writings leave urgent questions about justice and obligation, alongside projects she will never finish and arguments she cannot revise.',
    quote: {
      text: 'There is something sacred in every human being.',
      work: 'Human Personality',
      locator: 'Opening discussion of the sacred; Écrits de Londres et dernières lettres, Gallimard, 1957, pp. 9–44.',
      translation,
      url: 'https://fr.wikisource.org/wiki/Écrits_de_Londres_et_dernières_lettres/Écrits_de_Londres/01',
      note: 'La Personne et le Sacré, written in 1943. The essay distinguishes the vulnerable human being from an abstract concept of personality; collected posthumously.',
    },
    scene: 'models/chapter-11.glb',
    poster: 'posters/chapter-11.webp',
  },
  {
    id: 12,
    slug: 'the-pages-keep-opening',
    title: 'The pages keep opening',
    period: '1947 onward',
    place: 'An unfinished conversation',
    idea: 'The real',
    paragraph: 'After her death, friends and editors turn manuscripts into books. Readers encounter a thinker of unusual courage and troubling severity, including hostile judgments about Judaism. Her work invites argument as much as admiration. These pages end with a practice she kept returning to: giving the world, and the people within it, our undivided attention.',
    quote: {
      text: 'Beauty is something to which we can pay attention.',
      work: 'Gravity and Grace',
      locator: 'Beauty, fragment following the discussion of contemplation; La Pesanteur et la Grâce, Plon, 1948, pp. 170–174.',
      translation,
      url: 'https://fr.wikisource.org/wiki/La_Pesanteur_et_la_Grâce/33',
      note: 'From the 1940–1942 notebooks, selected and arranged by Gustave Thibon for the posthumous collection first published in 1947.',
    },
    scene: 'models/chapter-12.glb',
    poster: 'posters/chapter-12.webp',
  },
];
