import type { Chapter } from '../types';

const translation = 'English translation prepared for this project from the French original.';

/** Sources, edition details, and editorial decisions are recorded in docs/SOURCES.md. */
export const chapters: Chapter[] = [
  {
    id: 1,
    slug: 'a-restless-curiosity',
    title: 'A restless curiosity',
    period: '1909–1925',
    place: 'Paris',
    idea: 'Truth',
    paragraph: 'Born in Paris in 1909, Simone Weil grows up in a comfortable, secular Jewish family. Her brother André excels at mathematics, and she worries that she cannot match him. Yet she comes to believe that anyone can seek truth through patient attention. This conviction will guide her from books and classrooms into the lives of people whose suffering is often ignored.',
    quote: {
      text: 'By truth I also meant beauty, virtue, and every good.',
      work: 'Spiritual Autobiography',
      locator: 'Letter IV, paragraph on the meaning of truth; Attente de Dieu, La Colombe, 1950, pp. 69–89.',
      translation,
      url: 'https://fr.wikisource.org/wiki/Attente_de_Dieu/Autobiographie_spirituelle',
      note: 'Written to Joseph-Marie Perrin around 15 May 1942, looking back on adolescence; published posthumously.',
    },
    scene: 'models/chapter-01.glb',
    poster: 'posters/chapter-01.webp',
  },
  {
    id: 2,
    slug: 'learning-to-see',
    title: 'Learning to see',
    period: '1925–1931',
    place: 'Paris',
    idea: 'Learning',
    paragraph: 'That search for truth leads Simone to philosophy. She studies with the teacher Alain, enters the École normale supérieure in 1928, and writes about Descartes. She learns to examine ideas carefully, including her own. Later, she will explain why study matters beyond examinations: it trains us to look closely, admit uncertainty, and keep learning instead of rushing to an answer.',
    quote: {
      text: 'The intelligence can only be led by desire.',
      work: 'On the Right Use of School Studies',
      locator: 'Paragraph contrasting will and desire; Attente de Dieu, La Colombe, 1950, pp. 113–123.',
      translation,
      url: 'https://fr.wikisource.org/wiki/Attente_de_Dieu/Réflexions_sur_le_bon_usage_des_études_scolaires_en_vue_de_l’Amour_de_Dieu',
      note: 'A later religious reflection, written in 1941–1942; not a quotation from her student years. Published posthumously.',
    },
    scene: 'models/chapter-02.glb',
    poster: 'posters/chapter-02.webp',
  },
  {
    id: 3,
    slug: 'beyond-the-classroom',
    title: 'Beyond the classroom',
    period: '1931–1934',
    place: 'Le Puy · Auxerre · Roanne',
    idea: 'Solidarity',
    paragraph: 'In 1931, Simone becomes a philosophy teacher. She also teaches workers, supports unemployed people, and joins local campaigns. The questions she studied now meet people struggling to earn a living. For her, philosophy must help us understand how others actually live. Her fierce commitment can make her difficult company, but she refuses to keep thought separate from action.',
    quote: {
      text: 'The reality of life is not sensation, but activity.',
      work: 'Letter to a Student',
      locator: 'Paragraph on sensation and activity; La Condition ouvrière, Gallimard, 1951, pp. 23–28.',
      translation,
      url: 'https://fr.wikisource.org/wiki/La_Condition_ouvrière/03',
      note: 'Letter dated 1934 in this edition, written after she entered factory work; collected posthumously.',
    },
    scene: 'models/chapter-03.glb',
    poster: 'posters/chapter-03.webp',
  },
  {
    id: 4,
    slug: 'who-holds-the-power',
    title: 'Who holds the power?',
    period: '1932–1934',
    place: 'Germany · France',
    idea: 'Freedom',
    paragraph: 'During these teaching years, a visit to Germany in 1932 brings Simone face to face with the rise of Nazism. She also questions revolutionary movements on the left. Replacing a ruler, she argues, does not guarantee freedom. Workers need a say in their work, not simply new people giving orders. She begins asking how power itself can be changed.',
    quote: {
      text: 'Thus all power is unstable.',
      work: 'Reflections on Liberty and Social Oppression',
      locator: 'Analysis of Oppression, paragraph on the instruments of power; Oppression et Liberté, Gallimard, 1955, pp. 80–112.',
      translation,
      url: 'https://fr.wikisource.org/wiki/Oppression_et_Liberté/05/03',
      note: 'Written in 1934; published in this posthumous collection in 1955.',
    },
    scene: 'models/chapter-04.glb',
    poster: 'posters/chapter-04.webp',
  },
  {
    id: 5,
    slug: 'inside-the-factory',
    title: 'Inside the factory',
    period: '1934–1935',
    place: 'Paris',
    idea: 'Labor',
    paragraph: 'To test these ideas against daily life, Simone takes leave from teaching and enters factory work in 1934. Repetitive tasks, demanding supervisors, and exhaustion leave little room to think. She discovers that humiliation can silence people rather than make them rebel. Her notebooks record that experience. Unlike many colleagues, however, she has the option of returning to another life.',
    quote: {
      text: 'To think is to go more slowly.',
      work: 'Letter to a Student',
      locator: 'Paragraph describing mechanical work and speed; La Condition ouvrière, Gallimard, 1951, pp. 23–28.',
      translation,
      url: 'https://fr.wikisource.org/wiki/La_Condition_ouvrière/03',
      note: 'Letter dated 1934 in this edition, written from her factory experience; collected posthumously.',
    },
    scene: 'models/chapter-05.glb',
    poster: 'posters/chapter-05.webp',
  },
  {
    id: 6,
    slug: 'a-cause-and-its-cruelty',
    title: 'A cause and its cruelty',
    period: '1936',
    place: 'Barcelona · Aragon',
    idea: 'Conscience',
    paragraph: 'Her wish to stand beside people facing injustice next takes Simone to Spain. In 1936, despite her opposition to war, she joins an anarchist unit fighting Franco’s forces. An accidental burn ends her brief service. She remains disturbed by the casual cruelty of some comrades. Supporting their cause, she concludes, cannot excuse ignoring the suffering they inflict on others.',
    quote: {
      text: 'One leaves as a volunteer, with ideas of sacrifice…',
      work: 'Letter to Georges Bernanos',
      locator: 'Paragraph on volunteering; L’Espagnole, Abrüpt, 2018, pp. 31–40.',
      translation,
      url: 'https://fr.wikisource.org/wiki/L’Espagnole/03',
      note: 'Usually dated 1938; a retrospective letter about 1936. The ellipsis marks the continuation into her criticism of the war.',
    },
    scene: 'models/chapter-06.glb',
    poster: 'posters/chapter-06.webp',
  },
  {
    id: 7,
    slug: 'at-the-threshold',
    title: 'At the threshold',
    period: '1935–1938',
    place: 'Portugal · Assisi · Solesmes',
    idea: 'Grace',
    paragraph: 'Alongside these political struggles, Simone’s spiritual life is changing. A Portuguese procession in 1935, prayer in Assisi in 1937, and chanting at Solesmes in 1938 draw her toward Christianity. She later describes feeling Christ’s presence while reciting a poem. Faith offers a new way to understand suffering, although her questions about the Church prevent an easy sense of belonging.',
    quote: {
      text: 'Christ himself descended and seized me.',
      work: 'Spiritual Autobiography',
      locator: 'Letter IV, paragraph following the account of Herbert’s poem; Attente de Dieu, La Colombe, 1950, pp. 69–89.',
      translation,
      url: 'https://fr.wikisource.org/wiki/Attente_de_Dieu/Autobiographie_spirituelle',
      note: 'Written around 15 May 1942, recounting her own understanding of the earlier experience; published posthumously.',
    },
    scene: 'models/chapter-07.glb',
    poster: 'posters/chapter-07.webp',
  },
  {
    id: 8,
    slug: 'what-force-makes-of-us',
    title: 'What force makes of us',
    period: '1939–1940',
    place: 'Paris · Marseille',
    idea: 'Force',
    paragraph: 'When war returns to Europe, Simone comes to believe that Nazi aggression must be resisted. She leaves Paris with her family as German forces advance in 1940. Reading Homer’s Iliad, she connects ancient warfare with the violence around her. Force, she argues, makes people seem like objects to be used or destroyed. Even those who wield it become its prisoners.',
    quote: {
      text: 'Force turns anyone subjected to it into a thing.',
      work: 'The Iliad, or the Poem of Force',
      locator: 'Opening definition of force; La Source grecque, Gallimard, 1953, pp. 11–42.',
      translation,
      url: 'https://fr.wikisource.org/wiki/La_Source_grecque/01/L’Iliade,_ou_le_poème_de_la_force',
      note: 'Written in 1939–1940 and published in Cahiers du Sud in 1940–1941, under the name Émile Novis. This French edition is posthumous.',
    },
    scene: 'models/chapter-08.glb',
    poster: 'posters/chapter-08.webp',
  },
  {
    id: 9,
    slug: 'the-work-of-attention',
    title: 'The work of attention',
    period: '1940–1942',
    place: 'Marseille · Ardèche',
    idea: 'Attention',
    paragraph: 'Settling in Marseille, Simone continues writing and later works in the grape harvest. Conversations with a priest, Joseph-Marie Perrin, and a writer, Gustave Thibon, deepen her thinking about attention. Against a world that reduces people to objects, she asks us to notice each person’s suffering without putting ourselves at the center. In her religious writing, such attention becomes prayer.',
    quote: {
      text: 'Absolutely unmixed attention is prayer.',
      work: 'Gravity and Grace',
      locator: 'Attention and Will, short fragment; La Pesanteur et la Grâce, Plon, 1948, pp. 134–142.',
      translation,
      url: 'https://fr.wikisource.org/wiki/La_Pesanteur_et_la_Grâce/26',
      note: 'From notebooks written in 1940–1942; selected and arranged after her death by Gustave Thibon. The collection first appeared in 1947.',
    },
    scene: 'models/chapter-09.glb',
    poster: 'posters/chapter-09.webp',
  },
  {
    id: 10,
    slug: 'what-gives-us-roots',
    title: 'What gives us roots',
    period: '1942–1943',
    place: 'New York · London',
    idea: 'Belonging',
    paragraph: 'In 1942, Simone leaves France with her parents for New York, then moves to London to work for the Free French resistance movement. She turns from the damage of war to the question of rebuilding. In The Need for Roots, she argues that people need meaningful work, community, and a shared past, alongside food and shelter. Belonging carries responsibilities toward others.',
    quote: {
      text: 'Every human being needs multiple roots.',
      work: 'The Need for Roots',
      locator: 'Part II, Uprootedness, opening paragraph; L’Enracinement, Gallimard, 1949, pp. 43–46.',
      translation,
      url: 'https://fr.wikisource.org/wiki/L’Enracinement/Partie_2',
      note: 'Written in London in 1943; published posthumously in 1949.',
    },
    scene: 'models/chapter-10.glb',
    poster: 'posters/chapter-10.webp',
  },
  {
    id: 11,
    slug: 'the-unfinished-task',
    title: 'The unfinished task',
    period: '1943',
    place: 'London · Ashford',
    idea: 'Obligation',
    paragraph: 'While working on these proposals in London, Simone becomes seriously ill. Tuberculosis and severe undernourishment lead to her death in Ashford on 24 August 1943, aged 34. Why she ate so little remains debated. Her life ends with manuscripts unfinished, but her central concern is clear: no person’s suffering should be dismissed because they lack money, status, or power.',
    quote: {
      text: 'There is something sacred in every human being.',
      work: 'Human Personality',
      locator: 'Opening discussion of the sacred; Écrits de Londres et dernières lettres, Gallimard, 1957, pp. 9–44.',
      translation,
      url: 'https://fr.wikisource.org/wiki/Écrits_de_Londres_et_dernières_lettres/Écrits_de_Londres/01',
      note: 'La Personne et le Sacré, written in 1943. The essay distinguishes the vulnerable human being from an abstract concept of personality; collected posthumously.',
    },
    scene: 'models/chapter-11.glb',
    poster: 'posters/chapter-11.webp',
  },
  {
    id: 12,
    slug: 'the-pages-keep-opening',
    title: 'The pages keep opening',
    period: '1947 onward',
    place: 'An unfinished conversation',
    idea: 'The real',
    paragraph: 'From 1947, friends and editors bring Simone’s unpublished manuscripts to readers as books. Her courage lies in testing ideas against experience, from the classroom to the factory and exile. Her harsh judgments about Judaism also demand criticism. She leaves us no simple example to imitate, but a lasting challenge: look carefully at other people, and take responsibility for what you see.',
    quote: {
      text: 'Beauty is something to which we can pay attention.',
      work: 'Gravity and Grace',
      locator: 'Beauty, fragment following the discussion of contemplation; La Pesanteur et la Grâce, Plon, 1948, pp. 170–174.',
      translation,
      url: 'https://fr.wikisource.org/wiki/La_Pesanteur_et_la_Grâce/33',
      note: 'From the 1940–1942 notebooks, selected and arranged by Gustave Thibon for the posthumous collection first published in 1947.',
    },
    scene: 'models/chapter-12.glb',
    poster: 'posters/chapter-12.webp',
  },
];
